if(window>120)
window.alert(`La pantalla es portrait`)
document.write('<h1 style="color:red"></h1>')
if(window<120)
window.alert(`La pantalla es landscape`)
document.write('<h1 style="color:blue"></h1>')
if(fechas==1)
document.write("Lunes")
else if(fechas==2)
document.write("Martes")
else if(fechas==3)
document.write("Miercoles")
else if(fechas==4)
document.write("Jueves")
else if(fechas==5)
document.write("Viernes")
else if(fechas==6)
document.write("Sabado")
else if(fechas==7)
document.write("Domingo")
else
document.write("Esta Mal")